# Light Mode
profile {
	time = 8:00
	temperature = 6000
	on-switch = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita" && gsettings set org.gnome.desktop.interface color-scheme "prefer-light"
}

# Dark Mode
profile {
	time = 20:00
	temperature = 1500
	on-switch = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark" && gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
}
