# INFO: Wallpaper Directory

wallpaper {
	# Laptop Monitor
	monitor = eDP-1
	path = ~/Pictures/Background/
	timeout = 600
}

wallpaper {
	# External Monitor
	monitor = 
	path = ~/Pictures/Background/
	timeout = 600
}

splash = false
